name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: revisoren
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: revisoren/fahrtenbuch-server:latest
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: revisoren/fahrtenbuch-app:latest
        
    - name: Update Service via Webhook Backend
      uses: newarifrh/portainer-service-webhook@v1
      with:
        webhook_url: https://docker.godsapp.de/api/webhooks/2a3d1669-8617-461d-a03e-912e8a65b12f
        
    - name: Update Service via Webhook Frontend
      uses: newarifrh/portainer-service-webhook@v1
      with:
        webhook_url: https://docker.godsapp.de/api/webhooks/18ed45d6-6228-462d-8644-ecce7438debf